### ISSUE TITLE
12月万葉究楽部

### ISSUE THREAD

**Issue by yoshihara** [everyleaf/hiroba#8]
## テーマ

test-unit
## 日時
- 12/19(金) 18:30~
## 担当者
- @yoshihara
## ネタ
- test-unit
## TODO

資料とリポジトリへのリンク
lesson4がbundle exec rakeで動かせないのを直す

**Comment by yoshihara** [comment]
#KPT

## KEEP
- ソースコード用意してあった
- ハンズオンよかった（{≡･ｪ･≡}さんのをパクっただけ
- １時間でおわった
- 久しぶりに参加できた
- シュークリームby(・ω<)先生でエネルギーがでた

## PROBLEM
- テストうごかないのがあった
- お通夜
- 参加できない人がいた...
- 開催日変更通知が本山先生に伝わってなかった

## TRY
- 公開
- 次回の人：
  - 1/9 or 16
  - @upinetree 先生でなにか（react.jsとかRails4.2とかRubyとか）

**Comment by sakuma** [comment]
:+1:

**Comment by tatsuosakurai** [comment]
@sakuma :+1:

**Comment by den8** [comment]
@sakuma :+1:

**Comment by uu59** [comment]
@sakuma :+1:

**Comment by publichtml** [comment]
@sakuma :+1:

**Comment by mokkunp** [comment]
@sakuma :+1:

**Comment by to0526** [comment]
@sakuma :+1:
